language: node_js
node_js:
- 7
before_script:
- mv env.yml.dist env.yml
- sed -i "s#\$FIREBASE_API_KEY#$FIREBASE_API_KEY#g" env.yml
- sed -i "s#\$FIREBASE_DATABASE_URL#$FIREBASE_DATABASE_URL#g" env.yml
- sed -i "s#\$BOT_TOKEN#$BOT_TOKEN#g" env.yml
- sed -i "s#\$BOT_WEBHOOK_URL#$BOT_WEBHOOK_URL#g" env.yml
script:
- RUN_ENV=lambda serverless deploy
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_1c6d140d8538_key -iv $encrypted_1c6d140d8538_iv
  -in firebase-credentials.prod.json.enc -out firebase-credentials.prod.json -d
