service: sumlife
plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 10

functions:
  sumlife-set-webhook:
    handler: ./src/functions/setWebhook.setWebhook
    environment: ${file(./env.yml)}
  sumlife-ask-questions:
    handler: ./src/functions/askQuestions.askQuestions
    environment: ${file(./env.yml)}
    events:
      - schedule: rate(30 minutes)
  sumlife-api:
    handler: ./src/functions/exportData.exportData
    environment: ${file(./env.yml)}
    events:
      - http:
          path: api/{token}
          method: get 
          request: 
            parameters: 
              paths: 
                token: true
  sumlife-webhook:
    handler: ./src/functions/webhook.webhook
    environment: ${file(./env.yml)}
    events:
      - http:
          path: webhook/{token}
          method: post
          request: 
            parameters: 
              paths: 
                token: true
